apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  labels:
    app: contador
    tier: frontend
spec:
  # Replicas
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: contador-python
        image: fams/contador:latest
        env:
        - name:  REDIS_HOST
          value: redis.prd.svc.cluster.local
        - name:  REDIS_PORT
          value: "63797"
